# Site Settings
baseurl: ""
url : "https://zairewilson20.github.io"

# Blog Settings
theme_settings :
  title : Zaire Wilson
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/ZAvatar.webp
    username : Zaire Wilson
    description : Programmer of Games, Watcher of Anime, Father of Cats
    experience :
      - start : January 2022
        end : June 2024
        experience : GOLF+, Software Engineer
      - start : July 2021
        end : January 2022
        experience : Metagaming Studios, Software Engineer
      - start : May 2019
        end : January 2020
        experience : Rensselaer Polytechnic Institute, Undergrad Researcher
    skills : 
      - skill : C#
        value : 85  # Percent value       
      - skill : Python
        value : 80  # Percent value      
      - skill : C++
        value : 75  # Percent value      
      - skill : Unity
        value : 85  # Percent value      
      - skill : Unreal
        value : 60  # Percent value          
      - skill : HTML5 & CSS
        value : 50  # Percent       
      - skill : XAML
        value : 60  # Percent value
      - skill : React.js
        value : 60  # Percent value
    education :
      - start : August 2020
        end : May 2021
        school : Rensselaer Polytechnic Institute
        degree: M.S. Critical Game Design
      - start : August 2016
        end : May 2020
        school : Rensselaer Polytechnic Institute
        degree: B.S. Game and Simulation, Arts and Science + Computer Science

        
  # Icons
  icons :
    email:  zaire.r.wilson@gmail.com
    linkedin:  https://www.linkedin.com/in/zairewilson/ 
    github: ZaireWilson20
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
